# Generated by Django 4.1 on 2022-09-02 10:25

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_logo", models.ImageField(upload_to="")),
                ("school_name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=200)),
                ("district", models.CharField(max_length=100)),
                ("suburb", models.CharField(max_length=100)),
                ("school_lat", models.FloatField(blank=True, null=True)),
                ("school_lng", models.FloatField(blank=True, null=True)),
                ("school_motto", models.CharField(max_length=255)),
                ("school_about", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("school_address", models.TextField()),
                ("school_contact", models.CharField(max_length=255)),
                ("school_email", models.EmailField(max_length=255)),
                ("school_website", models.CharField(max_length=255)),
                (
                    "school_vacancy",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "school_academics",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "province",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.province",
                    ),
                ),
            ],
        ),
    ]
